### ISSUE TITLE
Error during runtest

### ISSUE THREAD

**Issue by mvvardhan** [kevinlin311tw/cvpr16-deepbit#4]
We get the following error when we do "make runtest". We use CUDA 7.5 on Ubuntu 14.04. Could you please suggest a solution for it?

https://github.com/kevinlin311tw/cvpr16-deepbit/blob/master/README.md

[----------] 4 tests from ImageDataLayerTest/0, where TypeParam = caffe::CPUDevice<float>

[ RUN      ] ImageDataLayerTest/0.TestShuffle

**\* Aborted at 1470802253 (unix time) try "date -d @1470802253" if you are using GNU date ***

PC: @     0x2b17d11def20 (unknown)

**\* SIGSEGV (@0x0) received by PID 43804 (TID 0x2b17cbfc91c0) from PID 0; stack trace: ***

```
@     0x2b17d2301d40 (unknown)

@     0x2b17d11def20 (unknown)

@           0x569cac std::operator+<>()

@     0x2b17d1645117 caffe::ImageDataLayer<>::DataLayerSetUp()

@     0x2b17d1626ce3 caffe::BasePrefetchingDataLayer<>::LayerSetUp()

@           0x5519ea caffe::ImageDataLayerTest_TestShuffle_Test<>::TestBody()

@           0x7b4803 testing::internal::HandleExceptionsInMethodIfSupported<>()

@           0x7ab4e7 testing::Test::Run()

@           0x7ab58e testing::TestInfo::Run()

@           0x7ab695 testing::TestCase::Run()

@           0x7ae9d8 testing::internal::UnitTestImpl::RunAllTests()

@           0x7aec67 testing::UnitTest::Run()

@           0x44fd4a main

@     0x2b17d22ecec5 (unknown)

@           0x456169 (unknown)

@                0x0 (unknown)
```

make: **\* [runtest] Segmentation fault (core dumped)

**Comment by kevinlin311tw** [comment]
You could ignore the runtest error because I didn't write any code for runtest.
