### ISSUE TITLE
Change max_iter for training new model

### ISSUE THREAD

**Issue by dangkhoasdc** [kevinlin311tw/cvpr16-deepbit#7]
Hi, thank you for your working.

I just wonder how I can change `max_iter` parameter (in Optimization step) as your paper presented. In your example with Cifar I could not find where to change `max_iter`.

Thank you in advance.

**Comment by kevinlin311tw** [comment]
Check the solver. You can modify max_iter in the solver. FYI: http://caffe.berkeleyvision.org/tutorial/solver.html
